language: generic
sudo : required
service:
  - docker

before_install:
  - docker build -t gurugudi/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true gurugudi/docker-react npm run test -- -- coverage
